---
- name: "Apache installation using docker"
  hosts: prod
  become: true
  vars_files:
    - files/secrets/credentials.vault

  pre_tasks:
    - name: Install some package 
      package: name='{{ item }}' state=present
      when: ansible_distribution == "CentOS"
      loop:
        - epel-release
        - wget
        - git

    - name: download pip script
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py
        
    - name: install python-pip
      command: python2.7 /tmp/get-pip.py
    - name: Install docker python
      pip: name=docker-py
